### ISSUE TITLE
cannot load into worlds

### ISSUE THREAD

**Issue by KaputSpider45** [Kasax007/Modpack-Development#41] opened 2022-07-30 18:06 UTC
hey, im attempting to get this mod to play with friends and i download it and everything works fine for the first time i load up minecraft and create a world, but then when i close dreamcraft and restart it and try to join  a previously created world it gives the message "errors in the currently selected data pack have prevented the world from loading" it then gives me the option to play in safe mode however that wont even work no matter how many times i click it, and then the other option is to go to main menu and fix it manually but no matter what i change it still gives me the same error message, and then if i delete and reinstall the mod pack it will work for that first time again but not any time after that. please help if you can.

**Comment by Kasax007** [comment] 2022-08-01 14:02
What version of the modpack are you using and what operating system?

**Comment by KaputSpider45** [comment] 2022-08-01 15:36
The newest version that was just released a couple days ago

**Comment by Kasax007** [comment] 2022-08-02 09:22
So I assume you are on windows then? I haven't heard of anyone having this issue and it definitively is not supposed to happen. In the past issues like this only occurred on other operating systems like Linux f.ex. I don't know if there are crash logs or other logs you can upload here but they certainly would help to identify the issue.

**Comment by Jastyo** [comment] 2022-08-03 18:17
Me and my wife are also having the same issue with version 1.0.21, my wife is on Windows 10 and I'm on Windows 11. We both get the same messagen as orignal poster when we log back into a previously saved world.

**Comment by Kasax007** [comment] 2022-08-04 20:36
I am uploading a new version now. Hopefully, the issue fixed itself with new mod updates. Let me know if this has fixed your issue.

**Comment by Kasax007** [comment] 2022-08-05 09:08
Update: The version is still under review on the curse forge website, as soon as they release it, it will be available for download. Usually, it takes only a couple of minutes but it seems this time there is the need for a manual review which can take a bit longer.

**Comment by obamanomicon** [comment] 2022-08-05 15:11
I'm getting this same issue of "errors in the data packs" after restarting the pack after playing for a while. Another thing is when trying to create a new world after this causes the modpack to just crash entirely.

**Comment by Kasax007** [comment] 2022-08-05 15:57
As I said, the new version should hopefully have fixed this issue. I have done a lot of testing and haven't had the issue once in the new version. I have even contacted the support of curse forge to hopefully accelerate the approval of the new version. 
For now, the issue isn't on the community server, so if you are looking for a place to play the modpack, feel free to play there in the meantime :)

**Comment by Kasax007** [comment] 2022-08-05 15:59
Apparently, they don't verify strange files on Friday and Saturday, so I will release a hotfix version that hopefully bypasses the algorithmic check and gets approved instantly.

**Comment by obamanomicon** [comment] 2022-08-05 16:40
let's hope, I really like this pack.

**Comment by Kasax007** [comment] 2022-08-25 23:40
Seems to be fixed in the newest version?

**Closed by Kasax007** 2022-08-25 23:40 UTC
