### ISSUE TITLE
game start cash

### ISSUE THREAD

**Issue by stagie66** [Kasax007/Modpack-Development#31] opened 2022-04-01 13:14 UTC
after you press the start button of the mod and he tries to load the mod casht this mod immediately hope you can help me :D

Mfg stagie
[2022-04-01-5.log](https://github.com/Kasax007/Modpack-Development/files/8398005/2022-04-01-5.log)

https://prnt.sc/-l6R111uEl8r

**Comment by cdgab** [comment] 2022-04-01 13:55
same problem here ...

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kambrik'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:159)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kambrik'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:157)
	... 2 more
Caused by: java.lang.ExceptionInInitializerError
	at io.ejekta.kambrik.internal.KambrikMod.idOf(KambrikMod.kt:30)
	at io.ejekta.kambrik.logging.KambrikMarkers.createIdMarker(KambrikMarkers.kt:16)
	at io.ejekta.kambrik.logging.KambrikMarkers.<clinit>(KambrikMarkers.kt:12)
	at io.ejekta.kambrik.internal.KambrikPrelaunch.handleCustomEntryData(KambrikPrelaunch.kt:31)
	at io.ejekta.kambrik.internal.KambrikPrelaunch.onPreLaunch(KambrikPrelaunch.kt:18)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2588 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_2960.<clinit>(class_2960.java:25)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method owo(Ljava/lang/String;)Ljava/lang/String; in indrev.mixins.json:aprilfools.MixinTranslatableText from mod indrev failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap indrev-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 17 more

**Comment by stagie66** [comment] 2022-04-01 14:05
i hope he fix this fast :D

**Comment by cdgab** [comment] 2022-04-01 14:06
i hope it's fixeable

**Comment by Kasax007** [comment] 2022-04-01 14:06
Yes, the mod pack isn't playable today since the creators of Industrial Revolution thought adding an April fools feature that breaks the mod and therefore the entire mod pack making it unplayable would be a great idea.

**Comment by cdgab** [comment] 2022-04-01 14:07
damn 
unlucky

**Comment by Kasax007** [comment] 2022-04-01 14:07
I am trying my best to get an update out right now but with the new fabric version, there are other issues that came up that I couldn't fix yet. In the current dev build the game always crashes when trying to open quests.

**Comment by Kasax007** [comment] 2022-04-01 14:09
Yes

**Comment by stagie66** [comment] 2022-04-01 14:10
no, that can not be at all of fabric5 the mod works, play it garde;D

**Comment by Kasax007** [comment] 2022-04-01 14:10
> isn't she serious or how can you find something like that funny

It was supposed to work but it's a broken implementation that causes a crash.

**Comment by Kasax007** [comment] 2022-04-01 14:10
Maybe the other pack devs already fixed it.

**Comment by stagie66** [comment] 2022-04-01 14:11
ja gut das kann sein

**Comment by ktic** [comment] 2022-04-01 14:33
Same issue :(. Goodluck Kasax, rooting for you.

**Comment by Kasax007** [comment] 2022-04-01 14:37
Momentarily fix: Go to the mods folder, and delete the indrev jar file. Add the indrev jar file from this link: https://mega.nz/file/A8JmGJSR#MpE9Da9vKqNrVRHKjzEX63Oq5lFpcZOsofnb5lD_Xg8

**Comment by ktic** [comment] 2022-04-01 14:48
> Momentarily fix: Go to the mods folder, and delete the indrev jar file. Add the indrev jar file from this link: https://mega.nz/file/A8JmGJSR#MpE9Da9vKqNrVRHKjzEX63Oq5lFpcZOsofnb5lD_Xg8

Does this need to be done on the server as well?

**Comment by Kasax007** [comment] 2022-04-01 15:01
yes

**Comment by linaraincalzando** [comment] 2022-04-01 15:32
I literally changed the date on my computer for a dirty fix

**Comment by Kasax007** [comment] 2022-04-01 15:51
Fixed in the just-released version.

**Closed by Kasax007** 2022-04-01 15:51 UTC
